<a href="https://colab.research.google.com/github/Infanterick/Python/blob/master/Broadcasting%2C_Operaciones_l%C3%B3gicas%2C_concatenacion%2C_stacking_y_split_en_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadcasting y Operaciones lógicas
---



In [1]:
import numpy as np

## Broadcasting

Permite realizar operaciones en arrays de diferentes formas sin necesidad de duplicar datos.

Ejemplo: aplicar un descuento a los precios de todos los productos en un arreglo.

In [2]:
prices = np. array([100,200,300])   # Precio de los productos
discount = np.array([0.9])          # Descuento a aplicar
discount_prices = prices * discount # Precio final (con descuento)

print(discount_prices)

[ 90. 180. 270.]


In [8]:
prices = np.random.randint(100,500, size=(3,3)) # Creaamos una matrix 3x3 con valores aleatorios del 100 al 500.
discount = np.array([10,20,30])                 # Creamos un arreglo con los descuentos a aplicar.
discount_prices = prices - discount             # Precio final (con descuento).

print("Precios:\n", prices, "\n")
print("Precio final:\n", discount_prices)

Precios:
 [[108 378 136]
 [325 415 268]
 [179 335 119]] 

Precio final:
 [[ 98 358 106]
 [315 395 238]
 [169 315  89]]


## Operaciones Lógicas
Permiten realizar comparaciones en arrays y crear máscaras booleanas.

### Método ALL
Verifica si TODOS los elementos del arreglo cumplen con la condición dada y retorna True o False según sea el caso.

In [11]:
array = np.array([1,2,3,4,5])

print("Todos los valores son mayores a 0:", np.all(array > 0))
print("Todos los valores son menores a 5:", np.all(array < 5))

Todos los valores son mayores a 0: True
Todos los valores son menores a 5: False


### Método ANY
Verifica si algún elemento del arreglo cumple con la condición dada y retorna True o False según sea el caso.

In [12]:
print("Algún elemento es mayor a 0:", np.any(array > 0))
print("Algún elemento es menor a 5:", np.any(array < 5))

Algún elemento es mayor a 0: True
Algún elemento es menor a 5: True


## Concatenación
Permite unir (combinar) varios arreglos.

In [13]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])

In [16]:
concatenated = np.concatenate((array_b, array_a))
print(concatenated)

[4 5 6 1 2 3]


## Stacking
Permite apilar arreglos de manera vertical u horizontal.

In [ ]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])

In [17]:
# Stacking vertical (vstack)

v_stack = np.vstack((array_a, array_b))
print(v_stack)

[[1 2 3]
 [4 5 6]]


In [18]:
# Stackin horizontal (hstack)

h_stack = np.hstack((array_a, array_b))
print(h_stack)

[1 2 3 4 5 6]


## División de arreglos (split)
La división debe ser entre un multiplo de la longitud del arreglo.

In [28]:
array_c = np.arange(1,13)       # Creamos un arreglo en un rango del 1 al 12.
print(array_c)

splited = np.split(array_c, 3)  # Dividimos el arreglo en 3 partes
print(splited)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
